
name: Ontology testing

on: [push, pull_request, workflow_dispatch]

jobs:
  robot_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ROBOT
        run: |
          wget --quiet https://github.com/ontodev/robot/releases/download/v1.8.1/robot.jar
          curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot 
          chmod +x robot
          sudo mv ./robot /usr/local/bin
          sudo mv ./robot.jar /usr/local/bin
          echo "ROBOT version:"
          robot -V
      - name: test for ERRORs with ROBOT report
        run: |
          robot report --profile .github/report_profile.txt --input dfgfo.ttl
          robot report --profile .github/report_profile.txt --input dfgfo.owl
      - name: validate ontology against OWL DL profile
        run: |
          robot validate-profile --profile DL --input dfgfo.ttl
          robot validate-profile --profile DL --input dfgfo.owl
      - name: produce report
        run: |
          robot report --profile .github/report_profile.txt --input dfgfo.ttl --output report-ttl.txt
          robot report --profile .github/report_profile.txt --input dfgfo.owl --output report-owl.txt
      - name: report artifact
        uses: actions/upload-artifact@v2
        with:
          name: robot_reports
          path: report-*.txt